---
- hosts: bbb
  tasks:
  - name: "Show the BBB secret"
    command: "/usr/bin/bbb-conf --secret" 
    register: secret_result

  - name: "Debug the BBB secret"
    debug:
      var: secret_result.stdout 

...
