---
# tasks file for pg
- name: "PG | Add Ubuntu postgres repo"
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main'
    filename: 'pgdg'
  tags: pg

- name: "PG | Add an Apt signing key"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags: pg

- name: "PG | Install postgres & python packages for ansible modules"
  apt:
    name: "{{ pg_packages }}"
    allow_unauthenticated: true
    force_apt_get: true
  vars:
    pg_packages:
    - postgresql-12
    - postgresql-client-12
    - postgresql-contrib-12
    - libevent-dev
    - python-psycopg2
  tags: pg

- name: "PG | Create role" 
  postgresql_user:
    db: postgres
    name: "{{ pg_user }}" 
    password: "{{ pg_pass }}"
    encrypted: yes
    role_attr_flags: CREATEDB,SUPERUSER
  no_log: true
  become: true
  become_user: "{{ pg_owner }}"
  tags: pg

- name: "PG | Create the database"
  postgresql_db:
    name: "{{ pg_database }}"
    owner: "{{ pg_user }}"
  become: true
  become_user: "{{ pg_owner }}"
  tags: pg

- name: "PG | Change postgreSQL.conf"
  lineinfile:
   dest: "/etc/postgresql/12/main/postgresql.conf"
   regexp: "{{ item.regexp }}"
   line: "{{ item.line }}"
   backrefs: yes
   state: present
  with_items:
   - { regexp: '^#listen_addresses =', line: "listen_addresses = '*'" }
  tags: pg

- name: "PG | Grant access to db via ph_hba.conf"
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    regexp: '^# IPv4'
    line: "{{ item }}" 
    insertafter: "# IPv4 local connections:"
  with_items:
   - 'host    scalelite       scalelite       .academyofmine.net      md5'
   - 'host    scalelite       scalelite       172.18.0.0/16           trust' 
  tags: pg

- name: "Restart service postgres on replicas"
  systemd:
    state: restarted
    daemon_reload: yes
    name: postgresql@12-main.service
  tags: pg

...
